#ifndef RTMAUDIOCORE_EXPORT_H
#define RTMAUDIOCORE_EXPORT_H

#include <QtCore/qglobal.h>

#if defined(RTMAUDIOCORE_LIBRARY)
#  define RTMAUDIOCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTMAUDIOCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTMAUDIOCORE_EXPORT_H
