#ifndef RTMAUDIOCORE_GLOBAL_H
#define RTMAUDIOCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RTMAUDIOCORE_LIBRARY)
#  define RTMAUDIOCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTMAUDIOCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTMAUDIOCORE_GLOBAL_H
